import Head from "next/head";
import styles from "/styles/home/Home.module.css";
import Link from "next/link";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Login Account</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.shapeCont}>
        <div className={styles.shape} />
        <div className={styles.shape} />
        <div className={styles.shape} />
        <div className={styles.shape} />
      </div>

      <div className={styles.login}>
        <div className={styles.logo}>
          <img src="Instprofile.jpg" alt="logo" />
        </div>

        <div className={styles.Loginform}>
          <h1>Welcome back! Login to your account</h1>
          <input type="text" placeholder="E-mail. Ex:sample@gmail.com" />
          <input type="password" placeholder="Password ***" />
          <div className={styles.btn}>
            <Link href={"home"}>
              <button>Enter</button>
            </Link>
            <button>Recover</button>
          </div>
        </div>
        <div className={styles.time}>
          <h1>11:00 AM. Kigali, Rwanda</h1>
          <h2>
            18<sup>Th</sup> February, 2023
          </h2>

        </div>
      </div>
    </div>
  );
}
